#!/usr/bin/python3
import sys, re
rootdomain = ''
pattern = re.compile(r'(http(s)?:\/\/(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]).'+rootdomain+r'\/')

while True:
    try:
        origline = input()
    except EOFError:
        sys.exit(0)
    if not origline.strip():
        continue
    origline_l = list(filter(lambda x:x, origline.split())) # Parsing line
    url = origline_l[0]
    scheme = origline_l[-1] # http or https ?
    fp.write(origline)
    newurl = pattern.sub(r'\1/',url) # Removing the root domain
    newurl= scheme + '://'+ '/'.join(newurl.split("/")[2:]) # Replacing scheme
    with open('/var/log/squid/urlrewrite.log','a') as fp:
        fp.write('> '+origline+'\n'+'< '+newurl+'\n')
    print(newurl)
